### ISSUE TITLE
User profile breaks when place with comment is deleted

### ISSUE THREAD

**Issue by ekahialoha** [kanui624/Nomster#1]
• First, create a comment for a place
• Then destroy the place that's connected to the comment
• Then visit your user dashboard.

Result: `Something went wrong` error

**Comment by kanui624** [comment]
I have tested this and created the instance with the issue. I don't know if
you will see the other email thread, but I just wanted further
clarification on whether this bug my caused my my decision making or if the
bug was directed in a lesson.

**Comment by ekahialoha** [comment]
This bug is something the lessons do not cover. It's built into the application and meant as something for you to research on your own to implement the fix based on your research.

**Comment by kanui624** [comment]
I see, thank you.

**Comment by ekahialoha** [comment]
You are welcome.  Feel free to open a thread on Slack if you run into issues

**Comment by kanui624** [comment]
I'm assuming I was supposed to catch this before submitting. How do I
report that I've fixed the bug? Via email? or do I submit some other way?

**Comment by ekahialoha** [comment]
No, your application passed. You are good to go. :)

**Comment by kanui624** [comment]
okay lit 🔥
